#!/usr/bin/env ruby

require "heroku_deploy"

HerokuDeploy::Config.setup do |config|
  config.app = "blahblah"
  config.remote = "heroku"
  config.generate_url = "/generate_js_and_css"
end

app = HerokuDeploy::Rails.new
app.deploy